export const processSteps = [
  {
    id: 1,
    phase: 'Phase 01',
    title: 'Requirement Analysis',
    description: 'Deep dive into client needs and project scope. Every mission starts with intelligence gathering.',
    color: '#4a9eff',
    side: 'left',
    stat: '100% Clarity',
  },
  {
    id: 2,
    phase: 'Phase 02',
    title: 'UI/UX Wireframe',
    description: 'Sketching the battlefield. Every flow and interaction mapped before a single line of code.',
    color: '#a78bfa',
    side: 'right',
    stat: 'Every Flow Mapped',
  },
  {
    id: 3,
    phase: 'Phase 03',
    title: 'Architecture Design',
    description: 'Building the skeleton. Database schemas and API contracts engineered for scale.',
    color: '#34d399',
    side: 'left',
    stat: 'Built to Scale',
  },
  {
    id: 4,
    phase: 'Phase 04',
    title: 'Development',
    description: 'Full throttle execution. Clean code and reusable components built to last.',
    color: '#f59e0b',
    side: 'right',
    stat: 'Zero Shortcuts',
  },
  {
    id: 5,
    phase: 'Phase 05',
    title: 'Testing & Debug',
    description: 'No stone unturned. Unit tests and performance profiling — zero tolerance for bugs.',
    color: '#fb923c',
    side: 'left',
    stat: '0 Bug Tolerance',
  },
  {
    id: 6,
    phase: 'Phase 06',
    title: 'Deployment',
    description: 'Mission goes live. CI/CD pipelines and monitoring — smooth launch every time.',
    color: '#f472b6',
    side: 'right',
    stat: 'Smooth Every Time',
  },
  {
    id: 7,
    phase: 'Phase 07',
    title: 'Delivered',
    description: 'Mission accomplished. Client satisfaction and product standing strong.',
    color: '#ff6b6b',
    side: 'center',
    stat: 'Mission Complete',
    isLast: true,
  },
]
